"""Registry provenance attestation for the chosen version.

npm: the registry's attestation endpoint (the same one `npm audit signatures`
reads). Trusted publishing generates a SLSA provenance attestation and an npm
publish attestation, both Sigstore-signed.

PyPI: the PEP 740 integrity API. Attestations are generated by default when
publishing through Trusted Publishing with the official GitHub Action.

Two facts are recorded, because they mean different things:
  present          the chosen version carries an attestation
  package_attests  the package's latest release carries one, so the
                   maintainer has adopted trusted publishing

A missing attestation on a package whose latest release is attested is a
regression and blocks. A package that has never attested cannot be held to
provenance it does not publish; that is reported, counts against provenance
coverage, and the other three authorities carry the decision.

Residual to admit on stage: an attestation proves where the build ran, not
that the publisher intended it. Compromised CI mints valid attestations.
"""
from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import quote

import httpx

from ..versions import osv_ecosystem

NPM_ATTESTATIONS = "https://registry.npmjs.org/-/npm/v1/attestations/{spec}"
NPM_METADATA = "https://registry.npmjs.org/{name}"
PYPI_PROJECT = "https://pypi.org/pypi/{name}/json"
PYPI_RELEASE = "https://pypi.org/pypi/{name}/{version}/json"
PYPI_PROVENANCE = "https://pypi.org/integrity/{name}/{version}/{filename}/provenance"


@dataclass
class AttestationResult:
    supported: bool               # ecosystem has a registry attestation mechanism
    present: bool                 # the chosen version carries an attestation
    provenance: bool              # a build-provenance attestation specifically
    publish: bool                 # a registry publish attestation (npm)
    package_attests: bool = False  # the package's latest release is attested
    latest_version: str | None = None
    detail: str = ""
    error: str | None = None


def check(ecosystem: str, package: str, version: str, timeout: float = 20.0) -> AttestationResult:
    eco = osv_ecosystem(ecosystem)
    try:
        with httpx.Client(timeout=timeout) as client:
            if eco == "npm":
                return _npm(client, package, version)
            return _pypi(client, package, version)
    except httpx.HTTPError as exc:
        return AttestationResult(True, False, False, False, detail="registry unavailable", error=str(exc))


def _npm_kinds(client: httpx.Client, package: str, version: str) -> list[str]:
    spec = quote(f"{package}@{version}", safe="@")
    resp = client.get(NPM_ATTESTATIONS.format(spec=spec))
    if resp.status_code == 404:
        return []
    resp.raise_for_status()
    return [a.get("predicateType", "") for a in resp.json().get("attestations", [])]


def _npm(client: httpx.Client, package: str, version: str) -> AttestationResult:
    kinds = _npm_kinds(client, package, version)
    provenance = any("slsa.dev/provenance" in k for k in kinds)
    publish = any("npm/attestation" in k or k.endswith("/publish/v0.1") for k in kinds)
    latest = None
    latest_kinds: list[str] = []
    meta = client.get(NPM_METADATA.format(name=package))
    if meta.status_code == 200:
        latest = meta.json().get("dist-tags", {}).get("latest")
        if latest:
            latest_kinds = kinds if latest == version else _npm_kinds(client, package, latest)
    package_attests = bool(latest_kinds)
    if kinds:
        detail = f"{package}@{version} attested ({', '.join(kinds)})"
    elif package_attests:
        detail = f"no attestations for {package}@{version}, but latest {latest} is attested: regression"
    else:
        detail = f"no attestations for {package}@{version}; latest {latest or '?'} is unattested too (package publishes no attestations)"
    return AttestationResult(True, bool(kinds), provenance, publish, package_attests, latest, detail)


def _pypi_attested(client: httpx.Client, package: str, version: str) -> list[str]:
    resp = client.get(PYPI_RELEASE.format(name=package, version=version))
    if resp.status_code == 404:
        return []
    resp.raise_for_status()
    attested = []
    for f in resp.json().get("urls", []):
        prov = client.get(PYPI_PROVENANCE.format(name=package, version=version, filename=f["filename"]))
        if prov.status_code == 200:
            attested.append(f["filename"])
    return attested


def _pypi(client: httpx.Client, package: str, version: str) -> AttestationResult:
    attested = _pypi_attested(client, package, version)
    latest = None
    latest_attested: list[str] = []
    proj = client.get(PYPI_PROJECT.format(name=package))
    if proj.status_code == 200:
        latest = proj.json().get("info", {}).get("version")
        if latest:
            latest_attested = attested if latest == version else _pypi_attested(client, package, latest)
    package_attests = bool(latest_attested)
    present = bool(attested)
    if present:
        detail = f"{package}=={version} attested files: {', '.join(attested)}"
    elif package_attests:
        detail = f"no PEP 740 attestations for {package}=={version}, but latest {latest} is attested: regression"
    else:
        detail = f"no PEP 740 attestations for {package}=={version}; latest {latest or '?'} is unattested too (package publishes no attestations)"
    return AttestationResult(True, present, present, False, package_attests, latest, detail)
